<?php

/**
 * @file
 * Contains bs_modal_messages.page.inc.
 */


/**
 * Prepares variables for 'bs-modal' templates.
 *
 * Default template: bs-modal.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - items: An associative array containing the items of list group.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_bs_modal(array &$variables) {

}
